# Generated by Django 4.2.7 on 2025-09-18 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('max_equipos', models.PositiveIntegerField(default=0)),
                ('tiene_eliminatorias', models.BooleanField(default=False)),
                ('num_equipos_eliminatoria', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Eliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('tercer_lugar', 'Tercer Lugar'), ('final', 'Final')], max_length=50)),
                ('orden', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])])),
                ('color_principal', models.CharField(default='#000000', max_length=7)),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('formato_torneo', models.CharField(choices=[('liga', 'Liga'), ('eliminatoria', 'Eliminatoria'), ('mixto', 'Mixto (Liga + Eliminatoria)')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoEliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('goles_local_vuelta', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goles_visitante_vuelta', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('eliminatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.eliminatoria')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_eliminatoria_local', to='torneos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_eliminatoria_visitante', to='torneos.equipo')),
            ],
            options={
                'ordering': ['eliminatoria__orden', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='torneos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='torneos.equipo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.grupo')),
            ],
            options={
                'ordering': ['jornada', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])])),
                ('fecha_nacimiento', models.DateField()),
                ('numero_camiseta', models.PositiveIntegerField()),
                ('posicion', models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.jugador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.partido')),
                ('partido_eliminatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.partidoeliminatoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo'),
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneos.equipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
