# Generated by Django 4.2.7 on 2025-09-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goleador',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria'),
        ),
    ]
