# Generated by Django 4.2.7 on 2025-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_goleador_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
