# Generated by Django 4.2.7 on 2025-09-22 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_alter_partido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='torneos/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
