# Generated by Django 4.2.7 on 2025-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_torneo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='color1',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='color2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='color3',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
