# Generated by Django 4.2.7 on 2025-10-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_participacionjugador'),
        ('torneos', '0006_ubicacioncampo_partido_ubicacion'),
    ]

    operations = [
    ]
