# Generated by Django 4.2.7 on 2025-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_add_jugador_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacionjugador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
