# Generated by Django 4.2.7 on 2025-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_alter_participacionjugador_id'),
        ('torneos', '0011_add_verificacion_audit'),
    ]

    operations = [
    ]
