# Generated by Django 4.2.7 on 2025-10-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_merge_20251022_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoleadorJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('goleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='torneos.goleador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.partido')),
                ('partido_eliminatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneos.partidoeliminatoria')),
            ],
        ),
    ]
