# Generated by Django 4.2.7 on 2025-11-20 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0013_goleadorjornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='torneos.torneo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador_torneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador de Torneo',
                'verbose_name_plural': 'Administradores de Torneos',
            },
        ),
    ]
