# Generated by Django 4.2.7 on 2025-12-02 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0015_usuariocreado'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='reglamento',
            field=models.FileField(blank=True, help_text='Sube el reglamento del torneo (PDF, DOC, DOCX, ODT)', null=True, upload_to='torneos/reglamentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt'])]),
        ),
    ]
