# Generated by Django 4.2.7 on 2026-01-05 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0016_torneo_reglamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustePuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_ajuste', models.IntegerField(help_text='Cantidad de puntos a agregar (positivo) o quitar (negativo)')),
                ('razon', models.CharField(help_text='Motivo del ajuste (ej: penalización, corrección, etc.)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_puntos', to='torneos.equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Puntos',
                'verbose_name_plural': 'Ajustes de Puntos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
