# Generated by Django 4.2.7 on 2026-01-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0017_ajustepuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacioncampo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
