# Generated by Django 4.2.7 on 2026-01-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0018_ubicacioncampo_creado_por'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capitan',
            new_name='Representante',
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
    ]
