# Generated by Django 4.2.7 on 2026-01-06 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0020_arbitro_partido_arbitro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('registrar', 'Registrar')], max_length=20)),
                ('tipo_modelo', models.CharField(choices=[('partido', 'Partido'), ('resultado', 'Resultado de Partido'), ('jugador', 'Jugador'), ('equipo', 'Equipo'), ('representante', 'Representante'), ('categoria', 'Categoría'), ('grupo', 'Grupo'), ('arbitro', 'Árbitro'), ('goleador', 'Goleador'), ('participacion', 'Participación de Jugador'), ('ubicacion', 'Ubicación de Campo'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='torneos.torneo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['torneo', '-fecha_hora'], name='torneos_reg_torneo__b013fa_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='torneos_reg_usuario_11f874_idx')],
            },
        ),
    ]
