# Generated by Django 6.0.2 on 2026-03-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0023_torneoportada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneoportada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
