# Generated by Django 6.0.3 on 2026-03-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0024_alter_torneo_fecha_fin_alter_torneoportada_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='color_principal',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='color_secundario',
        ),
    ]
