# Generated by Django 6.0.3 on 2026-03-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0025_remove_equipo_color_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Formato de Torneo',
                'verbose_name_plural': 'Formatos de Torneo',
            },
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='formato_torneo',
        ),
        migrations.AddField(
            model_name='torneo',
            name='formatos',
            field=models.ManyToManyField(help_text='Selecciona los formatos de este torneo', related_name='torneos', to='torneos.formatotorneo'),
        ),
    ]
