# Generated by Django 6.0.3 on 2026-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0026_formatotorneo_remove_torneo_formato_torneo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='formatos',
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato_torneo',
            field=models.CharField(choices=[('copa', 'Copa'), ('liga', 'Liga'), ('copa_liga', 'Copa y Liga'), ('eliminatoria', 'Eliminatorias')], default='liga', max_length=50),
        ),
    ]
