# Generated by Django 6.0.3 on 2026-03-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0027_remove_torneo_formatos_torneo_formato_torneo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormatoTorneo',
        ),
    ]
