# Generated by Django 6.0.3 on 2026-03-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0028_delete_formatotorneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('copa', 'Copa'), ('liga', 'Liga'), ('copa_liga', 'Copa y Liga'), ('eliminatoria', 'Eliminatorias')], max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupos', to='torneos.equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneos.grupo')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo a Grupo',
                'verbose_name_plural': 'Asignaciones de Equipos a Grupos',
                'unique_together': {('equipo', 'grupo', 'formato')},
            },
        ),
    ]
