# Generated by Django 6.0.3 on 2026-03-31 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0029_equipogrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('ninguna', 'Ninguna'), ('amarilla', 'Tarjeta amarilla'), ('roja', 'Tarjeta roja')], default='ninguna', max_length=10)),
                ('cantidad_amarillas', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('tipo_roja', models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10')], max_length=4, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'unique_together': {('jugador', 'partido')},
            },
        ),
    ]
